Algoritmo "funcoesmatematicas"
// Disciplina  : O curso definitivo de Lógica de Programação. Do VisualG às principais linguagens do mercado: C, C++, Python, C# e Java
// Professor   : Nelio Alves
// Descrição   : 25. Funções matemáticas
// Autor       : Marcos Ferreira Shirafuchi
// Data atual  : 30/11/2024

Var

   x, y, z, a, b, c, d : real


Inicio

      x <- 2.0
      y <- 3.0
      z <- -7.0

      a <- Exp(x,y)

      escreval(a)
  
Fimalgoritmo