Algoritmo "teste_para3"
// Disciplina  : O curso definitivo de Lógica de Programação. Do VisualG às principais linguagens do mercado: C, C++, Python, C# e Java
// Professor   : Nelio Alves
// Descrição   : 66. Estrutura repetitiva para
// Autor       : Marcos Ferreira Shirafuchi
// Data atual  : 24/12/2024

Var


      i : inteiro

Inicio
      para i de 5 ate 1 passo -1 faca
	        escreval("Valor de i: ", i)
      fimpara
Fimalgoritmo