Algoritmo "teste_para"
// Disciplina  : O curso definitivo de Lógica de Programação. Do VisualG às principais linguagens do mercado: C, C++, Python, C# e Java
// Professor   : Nelio Alves
// Descrição   : 66. Estrutura repetitiva para
// Autor       : Marcos Ferreira Shirafuchi
// Data atual  : 24/12/2024

Var


      i : inteiro

Inicio
      para i de 1 ate 5 faca
	        escreval("Bom dia")
      fimpara
Fimalgoritmo