Algoritmo "teste_condicional1"
// Disciplina  : O curso definitivo de Lógica de Programação. Do VisualG às principais linguagens do mercado: C, C++, Python, C# e Java
// Professor   : Nelio Alves
// Descrição   : 42. Estrutura Condicional"
// Autor       : Marcos Ferreira Shirafuchi
// Data atual  : 02/12/2024

Var


  x : inteiro



Inicio

      x <- 5

      escreval("Bom dia")

      se x > 0 então
	      escreval("Boa tarde")
      fimse
      escreval("Boa noite")
  
Fimalgoritmo