Algoritmo "exemplo1"
// Disciplina  : O curso definitivo de Lógica de Programação. Do VisualG às principais linguagens do mercado: C, C++, Python, C# e Java
// Professor   : Nelio Alves
// Descrição   : 23. Processamento de dados
// Autor       : Marcos Ferreira Shirafuchi
// Data atual  : 30/11/2024

Var

   x, y : inteiro


Inicio

  x <- 5
  y <- 2 * x
  
  escreval(x)
  escreval(y)
  
Fimalgoritmo