Algoritmo "exemplo5"
// Disciplina  : O curso definitivo de Lógica de Programação. Do VisualG às principais linguagens do mercado: C, C++, Python, C# e Java
// Professor   : Nelio Alves
// Descrição   : 23. Processamento de dados
// Autor       : Marcos Ferreira Shirafuchi
// Data atual  : 30/11/2024
Var

   a : real
   b : inteiro

Inicio

      a <- 5.0
      b <- Int(a)

      escreval(b)

  
Fimalgoritmo