Algoritmo "exemplo3"
// Disciplina  : O curso definitivo de Lógica de Programação. Do VisualG às principais linguagens do mercado: C, C++, Python, C# e Java
// Professor   : Nelio Alves
// Descrição   : 23. Processamento de dados
// Autor       : Marcos Ferreira Shirafuchi
// Data atual  : 30/11/2024
Var

   b1, b2, h, area : real

Inicio

      b1 <- 6.0
      b2 <- 8.0
      h <- 5.0

      area <- (b1 + b2) / 2.0 * h;
      escreval(area)

  
Fimalgoritmo